name = "erhomai"
pages_build_output_dir = "app/dist"
compatibility_date = "2025-07-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "SEARCH_INDEX"
id = "5ac8a11a8f75447694ce796784093f62"
